# Generated by Django 6.0.7 on 2026-07-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Count of consecutive failed login attempts.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='locked_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp until which the user account remains locked.', null=True),
        ),
    ]
