# Generated by Django 6.0.7 on 2026-07-17 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_created_by_department_updated_by_and_more'),
        ('users', '0003_customuser_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The Super Admin who created this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, help_text='The store department assigned to this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='departments.department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='The Super Admin who last updated this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('RECEIVING', 'Receiving'), ('DATA_ENTRY', 'Data Entry'), ('SUPERVISOR', 'Supervisor'), ('MANAGER', 'Manager'), ('ACCOUNTS', 'Accounts'), ('AUDIT_MANAGER', 'Audit Manager')], default='DATA_ENTRY', max_length=30),
        ),
    ]
