# Generated by Django 6.0.7 on 2026-07-12 04:08

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='phone',
        ),
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(default='', help_text='Physical or billing address of the vendor.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='credit_days',
            field=models.PositiveIntegerField(default=0, help_text='Allowed credit payment window in days (must be greater than zero).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='gst_number',
            field=models.CharField(db_index=True, default='', help_text='Unique 15-character Goods and Services Tax Identification Number (GSTIN).', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='mobile_number',
            field=models.CharField(default='', help_text='Primary contact mobile number of the vendor.', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this vendor is active and selectable.'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(db_index=True, help_text='Unique trade name of the vendor (case-insensitive).', max_length=150),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_vendor_name_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.CheckConstraint(condition=models.Q(('credit_days__gte', 0)), name='credit_days_must_be_non_negative'),
        ),
    ]
