# Generated by Django 6.0.7 on 2026-07-12 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_initial'),
        ('departments', '0002_department_created_by_department_updated_by_and_more'),
        ('vendors', '0002_remove_vendor_contact_person_remove_vendor_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bill',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for bill rejection (reserved for workflow module).', null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated the bill details.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The total amount payable on the invoice.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(help_text='The date when the invoice was issued.'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(db_index=True, help_text='Invoice identifier (unique per vendor).', max_length=50),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the bill was registered.'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_by',
            field=models.ForeignKey(help_text='User who initially registered the bill.', on_delete=django.db.models.deletion.PROTECT, related_name='created_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='current_status',
            field=models.CharField(choices=[('RECEIVING', 'Receiving'), ('DATA_ENTRY', 'Data Entry'), ('SUPERVISOR', 'Supervisor'), ('DEPARTMENT_MANAGER', 'Department Manager'), ('ACCOUNTS', 'Accounts'), ('ACCOUNTS_CLEARED', 'Accounts Cleared')], db_index=True, default='RECEIVING', help_text='Current workflow state of the bill.', max_length=30),
        ),
        migrations.AlterField(
            model_name='bill',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Internal store department assigned to this bill (nullable initially).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='departments.department'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tracking_id',
            field=models.CharField(db_index=True, help_text='Auto-generated unique status tracking ID assigned by the Service Layer.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the bill was last modified.'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='vendor',
            field=models.ForeignKey(help_text='Associated vendor registering the invoice.', on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='vendors.vendor'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0.0)), name='bill_amount_must_be_positive'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('vendor', 'bill_number'), name='unique_vendor_bill_number'),
        ),
        migrations.RemoveField(
            model_name='bill',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='is_deleted',
        ),
    ]
