# Generated by Django 6.0.7 on 2026-07-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_bill_unique_together_bill_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='current_status',
            field=models.CharField(choices=[('RECEIVING', 'Receiving'), ('DATA_ENTRY', 'Data Entry'), ('SUPERVISOR', 'Supervisor'), ('DEPARTMENT_MANAGER', 'Department Manager'), ('ACCOUNTS', 'Accounts'), ('ACCOUNTS_CLEARED', 'Accounts Cleared'), ('HOLDING', 'Holding')], db_index=True, default='RECEIVING', help_text='Current workflow state of the bill.', max_length=30),
        ),
    ]
