# Generated by Django 6.0.7 on 2026-07-10 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('RECEIVING', 'Receiving'), ('DATA_ENTRY', 'Data Entry'), ('SUPERVISOR', 'Supervisor'), ('DEPARTMENT_MANAGER', 'Department Manager'), ('ACCOUNTS', 'Accounts'), ('ACCOUNTS_CLEARED', 'Accounts Cleared')], max_length=30, null=True)),
                ('to_status', models.CharField(choices=[('RECEIVING', 'Receiving'), ('DATA_ENTRY', 'Data Entry'), ('SUPERVISOR', 'Supervisor'), ('DEPARTMENT_MANAGER', 'Department Manager'), ('ACCOUNTS', 'Accounts'), ('ACCOUNTS_CLEARED', 'Accounts Cleared')], max_length=30)),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REASSIGN', 'Reassign')], max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User to whom the bill was reassigned during this step (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_reassignments', to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bills.bill')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_actions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow History',
                'verbose_name_plural': 'Workflow Histories',
                'db_table': 'workflow_history',
                'ordering': ['created_at'],
            },
        ),
    ]
