# Generated by Django 6.0.7 on 2026-07-12 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_bill_unique_together_bill_rejection_reason_and_more'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowhistory',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('Credit Note Pending', 'Credit Note Pending'), ('Price Difference', 'Price Difference'), ('Discount Pending', 'Discount Pending'), ('Other', 'Other')], help_text='Standard rejection reason code.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workflowhistory',
            name='reason_note',
            field=models.TextField(blank=True, help_text='Custom rejection remarks or details.', null=True),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='action',
            field=models.CharField(choices=[('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REASSIGN', 'Reassign')], db_index=True, help_text='The action taken in this workflow step.', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User to whom the bill was reassigned during this step (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_reassignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='bill',
            field=models.ForeignKey(help_text='The associated bill tracked in this step.', on_delete=django.db.models.deletion.PROTECT, related_name='history', to='bills.bill'),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='comments',
            field=models.TextField(blank=True, help_text='Remarks or reasons provided during this step.', null=True),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp of when the workflow action occurred.'),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('RECEIVING', 'Receiving'), ('DATA_ENTRY', 'Data Entry'), ('SUPERVISOR', 'Supervisor'), ('DEPARTMENT_MANAGER', 'Department Manager'), ('ACCOUNTS', 'Accounts'), ('ACCOUNTS_CLEARED', 'Accounts Cleared')], help_text='The previous status of the bill.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='performed_by',
            field=models.ForeignKey(help_text='The user who performed the transition action.', on_delete=django.db.models.deletion.PROTECT, related_name='workflow_actions_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='to_status',
            field=models.CharField(choices=[('RECEIVING', 'Receiving'), ('DATA_ENTRY', 'Data Entry'), ('SUPERVISOR', 'Supervisor'), ('DEPARTMENT_MANAGER', 'Department Manager'), ('ACCOUNTS', 'Accounts'), ('ACCOUNTS_CLEARED', 'Accounts Cleared')], db_index=True, help_text='The target status of the bill after this step.', max_length=30),
        ),
    ]
