# Generated by Django 6.0.7 on 2026-07-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_workflowhistory_reason_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowhistory',
            name='action',
            field=models.CharField(choices=[('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REASSIGN', 'Reassign'), ('HOLD', 'Hold'), ('RESUME', 'Resume')], db_index=True, help_text='The action taken in this workflow step.', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('RECEIVING', 'Receiving'), ('DATA_ENTRY', 'Data Entry'), ('SUPERVISOR', 'Supervisor'), ('DEPARTMENT_MANAGER', 'Department Manager'), ('ACCOUNTS', 'Accounts'), ('ACCOUNTS_CLEARED', 'Accounts Cleared'), ('HOLDING', 'Holding')], help_text='The previous status of the bill.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='to_status',
            field=models.CharField(choices=[('RECEIVING', 'Receiving'), ('DATA_ENTRY', 'Data Entry'), ('SUPERVISOR', 'Supervisor'), ('DEPARTMENT_MANAGER', 'Department Manager'), ('ACCOUNTS', 'Accounts'), ('ACCOUNTS_CLEARED', 'Accounts Cleared'), ('HOLDING', 'Holding')], db_index=True, help_text='The target status of the bill after this step.', max_length=30),
        ),
    ]
