# Generated by Django 6.0.7 on 2026-07-10 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_hash', models.CharField(help_text='Secure salted PBKDF2/SHA256 hash of the 6-digit OTP.', max_length=255)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Expiration timestamp (10 minutes from creation).')),
                ('is_used', models.BooleanField(default=False, help_text='Flag indicating whether this OTP has already been verified.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of OTP generation.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset OTP',
                'verbose_name_plural': 'Password Reset OTPs',
                'db_table': 'password_reset_otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at', 'is_used'], name='password_re_expires_be3b5c_idx')],
            },
        ),
    ]
